---
- name: Check service status
  hosts: all
  become: true

  vars:
    services_to_check:
      - httpd
      - sshd
      - firewalld
      - chronyd
      - podman

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Display service status
      ansible.builtin.debug:
        msg: "{{ item }}: {{ ansible_facts.services[item + '.service'].state | default('not found') }}"
      loop: "{{ services_to_check }}"
