---
# Install Ansible Core and Ansible Navigator, podman

- name: Install Ansible
  hosts: rh-control-group
  become: true

  tasks:
    - name: Install ansible-core with dnf
      ansible.builtin.dnf:
        name: ansible-core
        state: present

    - name: Install python3-pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install sshpass
      ansible.builtin.dnf:
        name: sshpass
        state: present

    - name: Install podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Check if container image exists
      ansible.builtin.command: podman image exists quay.io/rh_ee_swongpai/ansible-custom-ee:enablement-0
      register: image_exists
      changed_when: false
      failed_when: false
      become: false

    - name: Pull container image if not exists
      ansible.builtin.command: podman pull quay.io/rh_ee_swongpai/ansible-custom-ee:enablement-0
      when: image_exists.rc != 0
      changed_when: false
      become: false

    - name: Install ansible-navigator with pip
      ansible.builtin.pip:
        name: ansible-navigator
        state: present
        executable: pip3

    - name: Verify ansible installation
      ansible.builtin.command: ansible --version
      register: ansible_ver
      changed_when: false
      become: false

    - name: Verify ansible-navigator installation
      ansible.builtin.command: ansible-navigator --version
      register: nav_ver
      changed_when: false
      become: false

    - name: Show ansible version
      ansible.builtin.debug:
        msg: "{{ ansible_ver.stdout_lines[0] }}"

    - name: Show ansible-navigator version
      ansible.builtin.debug:
        msg: "{{ nav_ver.stdout_lines[0] }}"
