---
# Solution for Exercise 1: Basic Playbook Creation
# This playbook installs httpd package

- name: Install httpd package
  hosts: rh-target
  become: true

  pre_tasks:
    - name: Gather package facts before installation
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if httpd exists
      ansible.builtin.debug:
        msg: "httpd is {{ 'already installed' if 'httpd' in ansible_facts.packages else 'NOT installed' }}"

  tasks:
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present
        update_cache: true

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify httpd is installed
      ansible.builtin.assert:
        that:
          - "'httpd' in ansible_facts.packages"
        success_msg: "httpd is installed successfully"
        fail_msg: "httpd is NOT installed"

    - name: The httpd package verified
      ansible.builtin.debug:
        msg: "httpd package is installed and verified successfully!"
