---
- name: Render simple HTML template
  hosts: webservers
  become: true

  vars:
    site_title: "My Demo Site"
    welcome_message: "Hello from Ansible Template!"

  tasks:
    - name: Ensure web root exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Deploy index.html from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      vars:
        generated_by: "ansible"
      notify: Restart httpd

  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
