---
- name: Send Email with HTML Attachment
  hosts: devgcp
  gather_facts: yes
  vars_files:
    - vars/email_config.yml
  
  tasks:
    - name: Create HTML report
      template:
        src: templates/email-report.html.j2
        dest: /tmp/email-report.html
        mode: '0644'
      delegate_to: localhost

    - name: Send email with HTML attachment
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
        attach: "/tmp/email-report.html"
        secure: "{{ smtp_secure }}"
      delegate_to: localhost

    - name: Clean up temporary HTML file
      file:
        path: /tmp/email-report.html
        state: absent
      delegate_to: localhost
